name: repository_package
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

dependencies:
  dio: ^5.0.0
  async: ^2.8.2
  json_annotation: ^4.3.0
  shared_preferences: ^2.3.2
  cronet_http: ^1.3.2
  cupertino_http: ^1.5.1

dev_dependencies:
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  test: ^1.17.12